# load custom executable functions
for function in ~/.zsh/functions/*; do
  source $function
done

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Brew integration
. $(brew --prefix asdf)/asdf.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/gregmefford/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/gregmefford/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/gregmefford/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/gregmefford/google-cloud-sdk/completion.zsh.inc'; fi
